server {
    listen 80;
    listen [::]:80;
    server_name zipplz.xyz www.zipplz.xyz;

    # HTTP에서 HTTPS로 리디렉션
    location / {
        return 301 https://zipplz.xyz$request_uri;
    }
}

# HTTPS www 요청은 zipplz.xyz로 리디렉트
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.zipplz.xyz;

    ssl_certificate /opt/openvidu/owncert/certificate.cert;
    ssl_certificate_key /opt/openvidu/owncert/certificate.key;

    return 301 https://zipplz.xyz$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name zipplz.xyz;

    # SSL 설정
    ssl_certificate /opt/openvidu/owncert/certificate.cert;
    ssl_certificate_key /opt/openvidu/owncert/certificate.key;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    
    client_max_body_size 100M;

    location ~ /\.git {
        deny all;
        return 403; # 접근 거부 시 403 Forbidden 반환
    }

    location ~ /\. {
        deny all;
        return 403;
    }
    
    # 백업 파일, 아카이브 파일, 설정 파일 등 잠재적으로 민감한 특정 확장자 파일 접근 차단
    location ~* \.(bak|old|gz|tgz|bz2|zip|rar|tar|sql|log|txt|inc|conf)$ {
        deny all;
        return 403;
    }

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        
        # 디렉토리 리스팅(Directory Listing) 비활성화 (보안 강화)
        autoindex off;
		    
        # SPA 새로고침 처리
        try_files $uri $uri/ /index.html =404;
        
        # CORS 공통 설정
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Origin, Authorization, Accept, Content-Type, X-Requested-With';
    
    }

    # Backend API 프록시
    location /api {
        proxy_pass http://zipplz-backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # wss(web-socket) 설정
        proxy_http_version 1.1;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "upgrade";

        # OPTIONS 메소드에 대한 프리플라이트 요청 처리
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }
    }

    # OpenVidu 프록시
    location /openvidu {
        proxy_pass https://openvidu:443/;  # Docker Compose 내부 서비스 이름
        proxy_ssl_verify off;                # self-signed 인증서 무시

        # WebSocket
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # OpenVidu WebSocket 연결에 필요한 추가 헤더
        proxy_set_header Sec-WebSocket-Protocol $http_sec_websocket_protocol;
        
        # OPTIONS 프리플라이트
        if ($request_method = 'OPTIONS') {
            add_header 'Access-Control-Max-Age' 1728000;
            add_header 'Content-Type' 'text/plain charset=UTF-8';
            add_header 'Content-Length' 0;
            return 204;
        }

    }
}