services:
  # 원래는 ZIPPlZ-Plus-mysql 단락을 구성해야 하지만 이번에는 H2를 사용하므로 패스

  zipplz-backend:
    container_name: zipplz-backend
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - openvidu
      - kurento-media-server
    environment:
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/app/data/zipplz;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
      - SPRING_H2_CONSOLE_PATH=${spring_h2_console_path}
      - SPRING_DATASOURCE_USERNAME=${spring_datasource_username}
      - SPRING_DATASOURCE_PASSWORD=${spring_datasource_password}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.H2Dialect

      - OPENVIDU_URL=${OPENVIDU_URL}
      - OPENVIDU_SERVER_URL=${OPENVIDU_SERVER_URL}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
      - spring_jwt_secret=${spring_jwt_secret}
      - spring_security_oauth2_client_registration_google_client_id=${spring_security_oauth2_client_registration_google_client_id}
      - spring_security_oauth2_client_registration_google_client_secret=${spring_security_oauth2_client_registration_google_client_secret}
      - spring_security_oauth2_client_registration_google_redirect_uri=${spring_security_oauth2_client_registration_google_redirect_uri}
      - spring_security_oauth2_client_registration_kakao_client_id=${spring_security_oauth2_client_registration_kakao_client_id}
      - spring_security_oauth2_client_registration_kakao_client_secret=${spring_security_oauth2_client_registration_kakao_client_secret}
      - spring_security_oauth2_client_registration_kakao_redirect_uri=${spring_security_oauth2_client_registration_kakao_redirect_uri}
      - spring_data_mongodb_uri=${spring_data_mongodb_uri}
      - cloud_aws_credentials_accessKey=${cloud_aws_credentials_accessKey}
      - cloud_aws_credentials_secretKey=${cloud_aws_credentials_secretKey}
      - openai_api_key=${openai_api_key}

      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - TZ=Asia/Seoul

    volumes:
      - h2-data:/app/data
    networks:
      - spring-cloud-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - spring-cloud-network

  openvidu:
    image: openvidu/openvidu-server:2.29.0
    container_name: openvidu
    restart: unless-stopped
    ports:
      - "4443:4443"
      - "8888:8888"
    depends_on:
      - kurento-media-server
    environment:
      - DOMAIN_OR_PUBLIC_IP=${DOMAIN_OR_PUBLIC_IP}
      - OPENVIDU_SECRET=${OPENVIDU_SECRET}
      - OPENVIDU_URL=${OPENVIDU_URL}
      - CERTIFICATE_TYPE=${CERTIFICATE_TYPE}
      # - OPENVIDU_CUSTOM_CERTIFICATE=/opt/openvidu/owncert/certificate.cert
      # - OPENVIDU_CUSTOM_PRIVATE_KEY=/opt/openvidu/owncert/certificate.key
      - KMS_URIS=["ws://kurento-media-server:8888/kurento"]
      - HTTPS_PORT=443
    volumes:
      # - /opt/openvidu/owncert/cert.pem:/opt/openvidu/owncert/certificate.cert
      # - /opt/openvidu/owncert/key.pem:/opt/openvidu/owncert/certificate.key
      - /opt/openvidu/owncert/keystore.p12:/opt/openvidu/owncert/keystore.p12
      - /opt/openvidu/.env:/opt/openvidu/.env
    networks:
      - spring-cloud-network

  kurento-media-server:
    image: kurento/kurento-media-server:6.18.0
    container_name: kurento-media-server
    restart: unless-stopped
    environment:
      # STUN 서버 설정 (WebRTC P2P 통신 지원) - Google의 공용 STUN 서버 사용
      - KMS_STUN_IP=stun.l.google.com
      - KMS_STUN_PORT=19302
      # 미디어 트래픽을 위한 포트 범위 설정
      # 이 포트 범위(예: 30000-30050)는 호스트 서버의 방화벽에서 반드시 열려 있어야 합니다!
      - KMS_MIN_PORT=30000
      - KMS_MAX_PORT=30050
    networks:
      - spring-cloud-network

volumes:
  h2-data:
    driver: local

networks:
  spring-cloud-network:
    external: true
    name: zipplz-network
    driver: bridge
