services:
  zipplz-frontend:
    user: root
    container_name: zipplz-frontend
    build: ./frontend
    image: zipplz/zipplz-frontend
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /opt/openvidu/owncert/cert.pem:/opt/openvidu/owncert/certificate.cert
      - /opt/openvidu/owncert/key.pem:/opt/openvidu/owncert/certificate.key
    environment:
      TZ: Asia/Seoul
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    external: true
    name: zipplz-network
    driver: bridge
